<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="r100_mecanum_wheel">

  <xacro:include filename="$(find clearpath_platform_description)/urdf/r100/wheels/mecanum_roller.urdf.xacro"/>

  <!-- Origin of N-th Roller -->
  <xacro:macro name="mecanum_roller_origin" params="th side">
    <xacro:property name="mecanum_wheel_radius" value="0.06"/>
    <xacro:property name="mecanum_roller_angle" value="${45 * pi/180}"/>
    <!-- Standard -->
    <xacro:if value="${side==1}">
      <origin xyz="${mecanum_wheel_radius*cos(th)} 0 ${mecanum_wheel_radius*sin(th)}"
        rpy="${mecanum_roller_angle} ${-th} 0"/>
    </xacro:if>

    <!-- Flipped -->
    <xacro:if value="${side==-1}">
      <origin xyz="${mecanum_wheel_radius*cos(th)} 0 ${mecanum_wheel_radius*sin(th)}"
        rpy="${-mecanum_roller_angle} ${-th} 0"/>
    </xacro:if>
  </xacro:macro>

  <!-- Generate Rollers -->
  <xacro:macro name="r100_generate_mecanum_rollers" params="parent side count iteration">
    <xacro:if value="${iteration}">
      <!-- Add Roller -->
      <xacro:r100_mecanum_roller prefix="${prefix + '_' + str(iteration)}" parent="${parent}">
        <xacro:mecanum_roller_origin th="${radians(360/count*(iteration-1))}" side="${side}"/>
      </xacro:r100_mecanum_roller>

      <!-- Call Recursively -->
      <xacro:r100_generate_mecanum_rollers parent="${parent}" side="${side}" count="${count}" iteration="${iteration-1}"/>

    </xacro:if>
  </xacro:macro>


  <!-- Mecanum Wheel -->
  <xacro:macro name="r100_mecanum_wheel" params="parent prefix side *joint_pose">
    <!-- Add Wheel -->
    <link name="${prefix}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 ${(-side+1)/2*pi}"/>
        <material name="clearpath_light_grey"/>
        <geometry>
          <mesh filename="package://clearpath_platform_description/meshes/r100/mecanum_rim.stl" scale="${side} 1 1"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="0.034" length="0.05"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="0.0003234" ixy="0" ixz="0"
          iyy="0.0003234" iyz="0"
          izz="0.0004901"/>
      </inertial>
    </link>

    <gazebo reference="${prefix}_wheel_link">
      <material>Gazebo/LightGrey</material>
      <selfCollide>false</selfCollide>
      <mu1 value="0.5"/>
      <mu2 value="0.5"/>
      <!-- <fdir1 value="1 0 0"/> -->
    </gazebo>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="${parent}"/>
      <child link="${prefix}_wheel_link" />
      <xacro:insert_block name="joint_pose" />
      <axis xyz="0 1 0" />
    </joint>

    <!-- Add Rollers -->
    <xacro:r100_generate_mecanum_rollers parent="${prefix}_wheel_link" side="${side}" count="8" iteration="8"/>

  </xacro:macro>

</robot>
