<?xml version="1.0"?>
<!--
Software License Agreement (BSD)

\file      mounts.urdf.xacro
\authors   Luis Camero <lcamero@clearpathrobotics.com>
\copyright Copyright (c) 2022, Clearpath Robotics, Inc., All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that
the following conditions are met:
 * Redistributions of source code must retain the above copyright notice, this list of conditions and the
   following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
   following disclaimer in the documentation and/or other materials provided with the distribution.
 * Neither the name of Clearpath Robotics nor the names of its contributors may be used to endorse or promote
   products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WAR-
RANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, IN-
DIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<robot xmlns:xacro="http://ros.org/wiki/xacro"> 
    <!-- 
        Standard Mount: adds link (w/o geometry) at given position
        - assumes orientation of parent 
    -->
    <xacro:macro name="mount" params="name parent x:=0 y:=0 z:=0">
        <!-- Add Empty Mount -->
        <link name="${name}"/>
        <joint name="${name}_joint" type="fixed">
          <child link="${name}"/>
          <parent link="${parent}"/>
          <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <!--
    Partial Riser Mounts: adds standard mounts for the specified row at the specified level
    - requires that base_mounts have been added
    - level (i.e. height) is w.r.t. the base level
    -->
    <xacro:macro name="row_mounts" params="name parent_link parent_coordinate length spacing:=-0.08 z">
      <xacro:property name="parent_column" value="${parent_coordinate[0]}" />
      <xacro:property name="parent_row" value="${parent_coordinate[1]}" />
      <xacro:property name="chr" value="${dict(d97='a', d98='b', d99='c', d100='d', d101='e', d102='f', d103='g')}" />
      <xacro:if value="${length > 0}">
        <xacro:mount name="${name + '_' + chr['d' + str(python.ord(parent_column) + 7 - length)] + python.str(parent_row)}" parent_link="${parent_link}" y="${spacing * (7 - length)}" z="${z}" />
        <xacro:row_riser_mounts
          name="${name}"
          parent_link="${parent_link}"
          parent_coordinate="${parent_coordinate}"
          length="${length - 1}"
          spacing="${spacing}"
          z="${z}"
           />
      </xacro:if>
    </xacro:macro>

    <!-- 
        Base Row Mounts: adds standard mounts for row at base level (0) w.r.t base_link
    -->
    <xacro:macro name="base_row_mounts" params="row">
        <xacro:property name="x" value="${0.080 * (8 - row) - 0.2317}"/>
        <xacro:property name="z" value="0.23385"/>
        <xacro:mount name="A0${row}" parent="base_link" x="${x}" y="0.24" z="${z}"/>
        <xacro:mount name="B0${row}" parent="base_link" x="${x}" y="0.16" z="${z}"/>
        <xacro:mount name="C0${row}" parent="base_link" x="${x}" y="0.08" z="${z}"/>
        <xacro:mount name="D0${row}" parent="base_link" x="${x}" y="0.00" z="${z}"/>
        <xacro:mount name="E0${row}" parent="base_link" x="${x}" y="-0.08" z="${z}"/>
        <xacro:mount name="F0${row}" parent="base_link" x="${x}" y="-0.16" z="${z}"/>
        <xacro:mount name="G0${row}" parent="base_link" x="${x}" y="-0.24" z="${z}"/>
    </xacro:macro>

    <!-- 
        Base Plate Mounts: adds standard mounts for the entire base level (0) w.r.t. base_link 
    -->
    <xacro:macro name="base_mounts">
        <xacro:base_row_mounts row="1"/>
        <xacro:base_row_mounts row="2"/>
        <xacro:base_row_mounts row="3"/>
        <xacro:base_row_mounts row="4"/>
        <xacro:base_row_mounts row="5"/>
        <xacro:base_row_mounts row="6"/>
        <xacro:base_row_mounts row="7"/>
        <xacro:base_row_mounts row="8"/>
    </xacro:macro>

    <!-- 
        Riser Leg: standard leg for partial and full risers
        - 'height' is from parent to the bottom of riser (should substract thickness of riser)
    -->
    <xacro:macro name="riser_leg" params="name height parent *origin">
        <link name="${name}">
        <visual>
            <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
            <geometry>
              <box size="0.04 0.02 ${height}"/>
            </geometry>
            <material name="dark_grey"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
            <geometry>
              <box size="0.04 0.02 ${height}"/>
            </geometry>
            <material name="dark_grey"/>
        </collision>
        </link>
        <joint name="${name}_joint" type="fixed">
          <xacro:insert_block name="origin"/>
          <child link="${name}"/>
          <parent link="${parent}"/>
        </joint>
    </xacro:macro>

    <!-- 
        Post Quad: adds four posts in a rectangular configuration
    -->
    <xacro:macro name="quad_post" params="parent prefix length width height radius:=0.006 *origin">
    <link name="${prefix}">
      <!-- Top Left -->
      <visual>
        <material name="light_grey"/>
        <origin xyz="${length/2} ${width/2} ${height/2}"/>
        <geometry>
          <cylinder radius="${radius}" length="${height}"/>
        </geometry>
      </visual>
      <collision>
        <material name="light_grey"/>
        <origin xyz="${length/2} ${width/2} ${height/2}"/>
        <geometry>
          <cylinder radius="${radius}" length="${height}"/>
        </geometry>
      </collision>

      <!-- Top Right -->
      <visual>
        <material name="light_grey"/>
        <origin xyz="${length/2} ${-width/2} ${height/2}"/>
        <geometry>
          <cylinder radius="${radius}" length="${height}"/>
        </geometry>
      </visual>
      <collision>
        <material name="light_grey"/>
        <origin xyz="${length/2} ${-width/2} ${height/2}"/>
        <geometry>
          <cylinder radius="${radius}" length="${height}"/>
        </geometry>
      </collision>

      <!-- Bottom Left -->
      <visual>
        <material name="light_grey"/>
        <origin xyz="${-length/2} ${width/2} ${height/2}"/>
        <geometry>
          <cylinder radius="${radius}" length="${height}"/>
        </geometry>
      </visual>
      <collision>
        <material name="light_grey"/>
        <origin xyz="${-length/2} ${width/2} ${height/2}"/>
        <geometry>
          <cylinder radius="${radius}" length="${height}"/>
        </geometry>
      </collision>

      <!-- Bottom Right -->
      <visual>
        <material name="light_grey"/>
        <origin xyz="${-length/2} ${-width/2} ${height/2}"/>
        <geometry>
          <cylinder radius="${radius}" length="${height}"/>
        </geometry>
      </visual>
      <collision>
        <material name="light_grey"/>
        <origin xyz="${-length/2} ${-width/2} ${height/2}"/>
        <geometry>
          <cylinder radius="${radius}" length="${height}"/>
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}_joint" type="fixed">
      <child link="${prefix}"/>
      <parent link="${parent}"/>
      <xacro:insert_block name="origin"/>
    </joint>
  </xacro:macro>

  <!--
    Full Riser Mounts: adds standard mounts for a full riser at the specified level
  -->
  <xacro:macro name="full_riser_mounts" params="level">
    <xacro:row_riser_mounts row="1" level="${level}"/>
    <xacro:row_riser_mounts row="2" level="${level}"/>
    <xacro:row_riser_mounts row="3" level="${level}"/>
    <xacro:row_riser_mounts row="4" level="${level}"/>
    <xacro:row_riser_mounts row="5" level="${level}"/>
    <xacro:row_riser_mounts row="6" level="${level}"/>
    <xacro:row_riser_mounts row="7" level="${level}"/>
    <xacro:row_riser_mounts row="8" level="${level}"/>
  </xacro:macro>
</robot>