<?xml version="1.0"?>
<!--
Software License Agreement (BSD)

\file      mounts.urdf.xacro
\authors   Luis Camero <lcamero@clearpathrobotics.com>
\copyright Copyright (c) 2022, Clearpath Robotics, Inc., All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that
the following conditions are met:
 * Redistributions of source code must retain the above copyright notice, this list of conditions and the
   following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
   following disclaimer in the documentation and/or other materials provided with the distribution.
 * Neither the name of Clearpath Robotics nor the names of its contributors may be used to endorse or promote
   products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WAR-
RANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, IN-
DIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find clearpath_platform_description)/urdf/a200/decorations/pacs/common.urdf.xacro" />
  <!-- 
    Row Riser: add row length riser
      - within PACS grid framework, inputs are level (height) and row
      - adds legs and mounts
  -->
  <xacro:macro name="row_riser" params="level row">
    <!-- Infer from Level and Row -->
    <xacro:property name="prefix" value="riser_partial_${level}${row}"/>
    <xacro:property name="parent" value="D0${row}"/>
    <xacro:property name="height" value="${level*0.10}"/>
    <xacro:property name="thickness" value="0.00635"/>
    <!-- Partial Riser Plate Link -->
    <link name="${prefix}">
      <visual>
        <geometry>
          <mesh filename="package://clearpath_platform_description/meshes/a200/decorations/pacs/pacs_row_riser.stl"/>
        </geometry>
        <material name="dark_grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 ${thickness/2}" rpy="0 0 0"/>
        <geometry>
          <box size="0.11 0.59 ${thickness}"/> 
        </geometry>
        <material name="dark_grey"/>
      </collision>
    </link>
    <!-- Partial Riser Plate Joint -->
    <joint name="${prefix}_joint" type="fixed">
      <child link="${prefix}"/>
      <parent link="${parent}"/>
      <origin xyz="0 0 ${height - thickness}" rpy="0 0 0"/>
    </joint>

    <!-- Partial Riser Left Leg -->
    <xacro:riser_leg name="${prefix}_left_leg" height="${height - thickness}" parent="${parent}">
      <origin xyz="0 -0.27 0" rpy="0 0 0"/>
    </xacro:riser_leg>

    <!-- Partial Riser Right Leg -->
    <xacro:riser_leg name="${prefix}_right_leg" height="${height - thickness}" parent="${parent}">
      <origin xyz="0 0.27 0" rpy="0 0 0"/>
    </xacro:riser_leg>

    <!-- Partial Riser Mounts -->
    <xacro:row_riser_mounts row="${row}" level="${level}"/>
  </xacro:macro>
</robot>